inherit_from: .rubocop_todo.yml

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# コード長い
Layout/LineLength:
  Max: 500

Metrics/BlockLength:
  Max: 260

Style/MutableConstant:
  Enabled: false

# 追加した規約ファイル読込
require:
  - rubocop-rails

AllCops:
  NewCops: enable
  # Rubyバージョン指定
  TargetRubyVersion: 2.6
  # 除外
  Exclude:
    - "config.ru"
    - "bin/**"
    - "lib/**"
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - !ruby/regexp /old_and_unused\.rb$/
    - "vendor/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"
    - "lib/tasks/auto_annotate_models.rake"
